### ISSUE TITLE
Multiple random scrobbles of last played song hours later

### ISSUE THREAD

**Issue by danhash** [simple-last-fm-scrobbler/sls#537]
**SLS Version (required)**: 1.6.7
**Issue**: SLS scrobbles the last played Google Music and Poweramp songs multiple times, seemingly randomly, even when playing music in another app (like Amazon Music)
**Parameters**:
**What**: Multiple scrobbles
**Where**: SLS is in the background
**When**: At any point after pausing or stopping a song in Google Music or Poweramp
**Why**: Unknown
**How**: N/A
**Android Version**: 9
**Music Apps**: Google Music, Poweramp
**Detected Music Apps**: Poweramp, Podcast Addict, Amazon Music, VLC, Google Play Music, Qobuz, Spotify, YouTube, Firefox Preview
**Enabled Settings**: Scrobble, Notify now playing, When to scrobble: after every track, Also on playlist finish, Submit data on: Any network, Roaming
**Phone Model**: Samsung Note9
**Notes**: These two songs had one legitimate scrobble each, one from Google Music and one from Poweramp. Both were scrobbled many times, hours later. The only way I've found to make it stop when it happens is to force kill Poweramp and Google Music.
![image](https://user-images.githubusercontent.com/16405573/65164510-0c74fe00-da0b-11e9-812a-b81480ce1a0d.png)

**Comment by a93h** [comment]
yes, this can happen some times.
I'll look into handling it.
Thanks.

**Comment by a93h** [comment]
Did you leave Google Play Music and Poweramp open the whole time?

**Comment by danhash** [comment]
I didn't Force Close them, and neither app has a specific "exit" function, so both apps are probably "running" in some way in the background, but I'm not interacting with them at all. I assume the apps run until/unless the phone is running low on available resources (which isn't likely to happen on the Note9).

**Comment by danhash** [comment]
This happened again all night:

![image](https://user-images.githubusercontent.com/16405573/65257248-efa1fe80-dace-11e9-93d4-93c37130f37f.png)

This had never happened to me even once until the very recent update pushed out in the Play Store. Do we have a workaround for the time being? (Since Last.fm took away the little "x" next to each scrobble and you now have to go into a menu to delete a scrobble, it's quite a pain to delete the extra scrobbles.)

Thanks!

**Comment by danhash** [comment]
Who can I pay to fix this? Or can I downgrade to the previous, non-broken version? This was not an issue in the version a week ago; it is a bug that was introduced in the new version, and now it's happening every day, multiple times a day. It's a massive & app-breaking bug, and it's about to make me switch to a non-broken scrobbler. I love SLS and would love to support its development (in general, and the fixing of this bug in particular) with Patreon or similar. Can anyone help?

**Comment by a93h** [comment]
Hello friend,

Since it seems to be such an issue for you, maybe others agree also.
I will look into fixing this during the weekend.
Thanks very much for your communication.

I do not need payment, but if you know friends who can translate this app, I am in need of translators.

[OpenSkyApp Translator](https://os0hucc.oneskyapp.com/admin/project/dashboard/project/344237)

If you can edit and translate the code directly, rather than become a translator on OpenSky it is much easier for me.

Thanks,
Austin H.

**Comment by a93h** [comment]
I may have found the bug.
Would you be willing to test it?

**Comment by a93h** [comment]
[app-debug__custom.apk.zip](https://github.com/simple-last-fm-scrobbler/sls/files/3638972/app-debug__custom.apk.zip)

**Comment by danhash** [comment]
Thanks so much! Yes I will test. I don't know another language but would be
glad to help in whatever way I can.

**Comment by danhash** [comment]
I uninstalled SLS and installed the custom apk. It crashes immediately upon
startup.

**Comment by a93h** [comment]
Hello, could you try version 1.6.9 please?

**Comment by danhash** [comment]
Sure, where do I download 1.6.9?

**Comment by danhash** [comment]
I just got the Play store update to 1.7.0. Testing today.

**Comment by danhash** [comment]
Unfortunately, 1.7.0 still has this issue. It is scrobbling Google Music while I am using Poweramp (and it is also scrobbling Poweramp). What's weirder, it scrobbled two different Google Music tracks, during a period of time I didn't listen to anything in Google Music.

**Comment by a93h** [comment]
@danhash  thanks for the update.
I'm looking into how I can have this issue fixed.
I will review it again.
I think I can resolve this issue upon further investigation.
Apologies for the delay.

**Comment by a93h** [comment]
@danhash  Would you be willing to test the attached signed up to date apk?
I attached both the release and the debug version.
Please use the debug version if you can.
The release version will use less resources but I cannot view debug logs if something goes wrong with your install.
[app-debug_561.zip](https://github.com/simple-last-fm-scrobbler/sls/files/3836131/app-debug_561.zip)

**Comment by a93h** [comment]
## User Reporting Phantom Scrobbles With Apps Like Poweramp and Amazon Music #537

### Plan of Action

0. Potential Reasons: Floating (or Phantom) state changes from Poweramp or Amazon Music are being treated as invalid or valid state changes.
1. Test manually via using Poweramp and Amazon Music
2. Upon further investigation I found a bug in the way GenericControllerReceiver.java class uses it's data and the way AbstractPlayStatusReceiver.java uses what GenericControllerReceiver.java sends.
3. I think the problem should be resolved now.
4. Now I will test Poweramp and Amazon music myself to see.
5. I offered a report and explanation to the user and described potential fix #561

**Comment by danhash** [comment]
I uninstalled SLS and then installed the debug APK. However, when I launched the newly installed SLS, it still knew my Last.fm credentials, which makes me think something may not have been completely removed? How do I check if I'm using the correct APK?

The problem still exists on the APK. I'm listening in Poweramp, and it's scrobbling what I'm listening to in Poweramp along with the last played song in Amazon Music.

**Comment by danhash** [comment]
Since it was having so many issues, I disabled scrobbling for all the other apps except for Poweramp, but it didn't go back to scrobbling Poweramp correctly until I Force Stopped SLS and re-launched it.

I confirmed I'm running the debug APK by looking at the app in Settings. Still confused how the debug APK could have known my Last.fm credentials though.

**Comment by danhash** [comment]
It just sent a Now Playing notification for a track that's paused Spotify, and I haven't listened to Spotify for at least the last week (I don't even have an active subscription at the moment). Spotify was unchecked on the list of enabled apps (only Poweramp is enabled).

![image](https://user-images.githubusercontent.com/16405573/68691270-7b6d5f80-0541-11ea-9cdc-4b4490b7688a.png)

Let me know what info you need from me for debugging. Thanks!

**Comment by danhash** [comment]
It just scrobbled a track that's paused in Amazon Music, while I'm listening to Google Play Music and Google Play Music is the only player that's enabled in SLS.

I've been listening to Angels & Airwaves in Google Play Music, and the Explosions In the Sky track is from Amazon Music:

![image](https://user-images.githubusercontent.com/16405573/68896976-8fa88c80-06fa-11ea-864f-106bb64e31c0.png)

**Comment by 1719calvin** [comment]
+1 also facing this issue. Facing this using poweramp and soundcloud.

**Comment by a93h** [comment]
Please try this signed apk of my latest fixes, thanks.
[app-debug.zip](https://github.com/simple-last-fm-scrobbler/sls/files/3902826/app-debug.zip)

**Comment by a93h** [comment]
This following apk should function well.
Not 100% certain it will fix the phantom scrobbles.
[app-debug.zip](https://github.com/simple-last-fm-scrobbler/sls/files/3905015/app-debug.zip)

**Comment by danhash** [comment]
No random scrobbles yet. Continuing to test. Will let you know.

I do get a seemingly endless series of notifications of "new" music apps, including non-music apps (such as NY Times).

**Comment by danhash** [comment]
@a93h, I'm satisfied to say your latest debug version fixes the issue!

**Comment by a93h** [comment]
Ok great that's one bug down. 👍

**Comment by danhash** [comment]
Should I keep using this debug version until the next release?

**Comment by a93h** [comment]
Yes. If I patch any bugs you're concerned with, I would share a patched debug version in the issue thread (like above).
